### ISSUE TITLE
Pickle Core should use different default path for virtual environments

### ISSUE THREAD

**Issue by KIC** [shaypal5/cachier#57]
The nature of virtual envs is to support different versions. pickling to home essentially breaks the ability to cache pickles of objects from different versions. This can lead to very strange exceptions like fsnotify exceeding its limits.

Therefore I propose to have a path inside the venv if we are in a virtual environment.

**Comment by shaypal5** [comment]
Hmmm.  I see your point, but virtualenvs separate different Python installations, not complete environments of the OS.

For example, Python virtualenvs do not affect environment variables, which is the way cachier is configured.

Also, being very explicit about WHERE the cache is kept is important, since it can rapidly expand.
Doing this under the hood is bad UI/UX.

I suggest, at the minimum, that you add an environment variable that - if set - activates this non-intuitive behaviour.
Also, documentation must be added.

Finally, the main problem I see here is that this implementation does not adhere to the [XDG Base directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), so you have some convincing to do.

Let's discuss this more. :)
